.TH buzzbird 1 "6 January 2011" buzzbird "buzzbird"
.SH NAME
buzzbird \- wrapper script for starting buzzbird application via xulrunner

.SH SYNOPSIS
\fBbuzzbird

.SH DESCRIPTION
\fBbuzzbird\fP is a script that launches buzzbird via xulrunner.

.SH "BUGS"

None found, yet.

.SH SEE ALSO
.PD 0
.TP
\fBxulrunner\fP
.TP
\fBhttp://getbuzzbird.com\fP
.PD

.SH LICENSE
This software is licensed under MIT license.

.SH AUTHOR
This manpage was written by Jan Klepek <jan.klepek at gmail.com> and the utility was written by Mike Desjardins.

